name: Build

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
    - uses: actions/checkout@v7
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 10.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test PostgreSignalR.slnx --no-build --verbosity normal -m:1 --results-directory ./TestResults --blame-hang --blame-hang-timeout 2m --blame-hang-dump-type mini -- --stop-on-fail on
      timeout-minutes: 10
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: ./TestResults
        retention-days: 5
